#ifndef _H_MAIN
#define _H_MAIN

#include <SDL.h>
#include <SDL_mixer.h>

#define xstr(s) str(s)
#define str(s) #s

#define SCREEN_WIDTH					(320)
#define SCREEN_HEIGHT					(240)
#define SCREEN_BPP						(16)
#define FPS_LIMIT						(60)

#define GFX_DIR							"gfx/"
#define SFX_DIR							"sfx/"

#define KEY_LEFT						SDLK_LEFT
#define KEY_RIGHT						SDLK_RIGHT
#if defined(MIYOO)
#define KEY_ACCELERATE					SDLK_LALT
#else
#define KEY_ACCELERATE					SDLK_UP
#endif
#define KEY_NEXT_CM						SDLK_TAB
#define KEY_AI							SDLK_BACKSPACE
#define KEY_START						SDLK_RETURN
#define KEY_QUIT						SDLK_ESCAPE

enum SkillType
{
	SKILL_NONE,
	SKILL_GHOST,
	SKILL_ONIX,
	SKILL_UROBOROS,
	SKILL_END
};

enum SoundType
{
	ST_NONE,
	ST_CRUNCH,
	ST_BITE,
	ST_GHOST,
	ST_HARM,
	ST_ONIX,
	ST_UNLOCK,
	ST_DIE,
	ST_END
};

enum LevelType
{
	LT_CAGE,
	LT_POLYGON,
	LT_STAR,
	LT_NUM
};

enum Wobbliness
{
	W_ABSTEINER,
	W_NORMIE,
	W_BOOZER,
	W_NUM
};

enum MenuOptions
{
	MO_LEVELTYPE,
	MO_WOBBLINESS,
	MO_NUM
};

enum Food
{
	FRUIT_START = 0,
	FRUIT_ACAI = FRUIT_START,
	FRUIT_APPLE,
	FRUIT_APRICOT,
	FRUIT_AVOCADO,
	FRUIT_BANANAS,
	FRUIT_BLACKBERRY,
	FRUIT_BLUEBERRY,
	FRUIT_CACTUS_PEAR,
	FRUIT_CANTALOUPE,
	FRUIT_CHERRY,
	FRUIT_CINDERBERRY,			// fantasy
	FRUIT_COCONUT,
	FRUIT_CRANBERRY,
	FRUIT_DESTINYFRUIT,			// fantasy
	FRUIT_DRAGONFRUIT,
	FRUIT_FIG,
	FRUIT_GRAPES,
	FRUIT_GREEN_APPLE,
	FRUIT_HONEYDEW,
	FRUIT_LEMON,
	FRUIT_LIME,
	FRUIT_LYCHEE,
	FRUIT_MANGO,
	FRUIT_METALBERRY,			// fantasy
	FRUIT_ORANGE,
	FRUIT_OREBERRY,				// fantasy
	FRUIT_PASSIONFRUIT,			// fantasy
	FRUIT_PEACH,
	FRUIT_PEAR,
	FRUIT_PINEAPPLE,
	FRUIT_POMEGRANATE,
	FRUIT_RASPBERRY,
	FRUIT_SOULFRUIT,			// fantasy
	FRUIT_STRAWBERRY,
	FRUIT_TOMATO,
	FRUIT_WATERMELON,
	FRUIT_END,
	VEGE_START = 64,
	VEGE_ARTICHOKE = VEGE_START,
	VEGE_BEETS,
	VEGE_BLACK_BEANS,
	VEGE_BOKCHOY,
	VEGE_BRUSSELS_SPROUTS,
	VEGE_CABBAGE,
	VEGE_CAYENNE,
	VEGE_CORN,
	VEGE_CUCUMBER,
	VEGE_DEVILS_LETTUCE,		// fantasy
	VEGE_GARLIC,
	VEGE_GHOST_PEPPER,			// fantasy
	VEGE_GINGER,
	VEGE_GOLD_MUSHROOM,			// fantasy
	VEGE_GREEN_BEANS,
	VEGE_HABANERO,
	VEGE_JALAPENO,
	VEGE_JELLYROOT,				// fantasy
	VEGE_LEEK,
	VEGE_ONION,
	VEGE_PIXIE_BEANS,			// fantasy
	VEGE_POTATO,
	VEGE_PUMPKIN,
	VEGE_RADDISH,
	VEGE_RED_BEANS,
	VEGE_RED_BELLPEPPER,
	VEGE_RHUBARB,
	VEGE_SHROOM1,
	VEGE_SHROOM2,
	VEGE_SHROOM3,
	VEGE_SPINACH,
	VEGE_TURNIP,
	VEGE_YAM,
	VEGE_YELLOW_BELLPEPPER,
	VEGE_CARROT,
	VEGE_EGGPLANT,
	VEGE_END,
	FOOD_END = VEGE_END
};

extern int menu_options[];
extern SDL_Surface *screen;
extern int gamestate;
extern Mix_Chunk *sfx_chunks[];

#endif
